CREATE DATABASE tasksDb;

CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  completed ENUM('0', '1') DEFAULT '0',
  fechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);